openapi: 3.1.0
info:
  title: 测试文档
  version: 1.0.11
tags:
  - name: test
    description: 控件器的备注
paths:
  /test:
    get:
      tags:
        - test
      summary: api的备注
      responses:
        '200':
          description: 测试返回类型
          content:
            applicaton/json:
              schema: 
                type: integer