[package]
name = "swagger_tk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.131"
swagger_macro = { version = "0.1.0", path = "../swagger_macro" }
