[package]
name = "swagger_gen_aptx"
version = "0.1.0"
edition = "2021"
description = "@aptx specific renderers for swagger_gen"

[dependencies]
swagger_gen = { path = "../swagger_gen" }
Inflector = "0.11.4"
