[package]
name = "actix_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
actix-web = "4.9.0"
actix_extension = { version = "0.1.0", path = "../actix_extension" }
quote = "1.0.37"
syn = { version = "2.0.82", features = ["full"] }
